
- name: Launch PostgreSQL container
  docker_container:
    name: postgres_container
    image: pierrebaptisteaubert/tp-devops-database:latest
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
    env_file: /tmp/db.env
