- name: Remove existing Docker image (force pull workaround)
  docker_image:
    name: pierrebaptisteaubert/tp-devops-database:latest
    force: true
    state: absent

- name: Launch PostgreSQL container
  docker_container:
    name: postgres_container
    image: pierrebaptisteaubert/tp-devops-database:latest
    state: started
    restart_policy: unless-stopped
    networks:
      - name: app-network
    env_file: /tmp/db.env
